add_library(fima_lib
    src/helpers/get_directories_entries.cpp
    src/tui/commands/tree/tree_tui.cpp
    src/commands/create/directory.cpp
    src/commands/copy/directory.cpp
    src/tui/commands/ls/ls_tui.cpp
    src/commands/permissions.cpp
    src/commands/create/file.cpp
    src/commands/copy/file.cpp
    src/commands/rename.cpp
    src/commands/remove.cpp
    src/helpers/logger.cpp
    src/commands/tree.cpp
    src/commands/ls.cpp
    src/tui/tui.cpp
)
