coverage:
  round: nearest
  range: "75..100"

ignore:
  # pretty much useless to get the coverage, it isn't used in actual program
  - "src/tui/commands/tree/tree_tui.cpp"

  # impossible and/or useless to test them fully
  - "src/commands/trash/empty.cpp"
  - "include/utility/regex.h"
  - "include/fs/get_application_directories.h"
  - "include/theme.h"
