/*
 * src/mappings.cpp
 * include/mappings.h
 *
 * A utility to work with the program mappings (like icon to to name).
 *
 * Copyright (C) 2026 Giuliano De Amicis. All rights reserved.
 * This software is licensed under the GPL-3.0-or-later.
 * See LICENSE file for details.
 */

#pragma once

#include <filesystem>
#include <nlohmann/json.hpp>
#include <string_view>
#include <unordered_map>

namespace fima {

namespace mappings {

class Comments
{
  public:
    std::string_view single{ "" };
    std::string_view multiline_start{ "" };
    std::string_view multiline_end{ "" };

    std::string_view single_alt{ "" };
    std::string_view multiline_start_alt{ "" };
    std::string_view multiline_end_alt{ "" };

    Comments(std::string_view single,
             std::string_view multiline_start,
             std::string_view multiline_end,
             std::string_view single_alt          = "",
             std::string_view multiline_start_alt = "",
             std::string_view multiline_end_alt   = "")
      : single(single)
      , multiline_start(multiline_start)
      , multiline_end(multiline_end)
      , single_alt(single_alt)
      , multiline_start_alt(multiline_start_alt)
      , multiline_end_alt(multiline_end_alt) {};

    Comments(std::string_view single, std::string_view single_alt)
      : single(single)
      , single_alt(single_alt) {};

    Comments(std::string_view single)
      : single(single) {};

    Comments() {};

    [[nodiscard]] bool can_have_single_comment() const
    {
        return !(this->single.empty() && this->single_alt.empty());
    };
    [[nodiscard]] bool can_have_multiline_comment() const
    {
        return !((this->multiline_start.empty() && this->multiline_end.empty()) &&
                 this->multiline_start_alt.empty() && this->multiline_end_alt.empty());
    };
};

[[nodiscard]] Comments
get_language_comments(const std::filesystem::path& path);

[[nodiscard]] std::string_view
get_language_name(const std::filesystem::path& path);

[[nodiscard]] std::string
get_item_icon(const std::filesystem::path& path);

inline const std::unordered_map<std::string_view, Comments> map_language_family_comments{
    { "c_like", { "//", "/*", "*/" } },
    { "lisp_like", { ";" } },
    { "shell_like", { "#" } },
    { "markup", { "", "<!--", "-->" } },
    { "python", { "#", "\"\"\"", "\"\"\"", "", "\'\'\'", "\'\'\'" } },
    { "css", { "", "/*", "*/" } },
    { "text", {} },
    { "vim", { "\"" } },
    { "cmd", { "REM", "::" } },
    { "lua", { "--", "--[[", "--]]" } },
    { "react", { "", "{/*", "*/}" } },
    { "haskell", { "--", "{-", "-}" } },
    { "erlang", { "%" } },
    { "fortran", { "!" } },
    { "ada", { "--" } },
    { "ocaml", { "//", "(*", "*)" } },
    { "sql", { "--", "/*", "*/" } },
    { "coffeescript", { "#", "###", "###" } },
    { "prolog", { "%", "/*", "*/" } },
    { "wat", { ";;", "", "" } },
    { "cobol", { "*>", "", "" } },
};

inline const std::unordered_map<std::string_view, std::string_view> map_extension_language_family{
    { ".cpp", "c_like" },
    { ".cxx", "c_like" },
    { ".cc", "c_like" },
    { ".c", "c_like" },
    { ".h", "c_like" },
    { ".hpp", "c_like" },
    { ".hxx", "c_like" },
    { ".inl", "c_like" },
    { ".rs", "c_like" },
    { ".cs", "c_like" },
    { ".js", "c_like" },
    { ".ts", "c_like" },
    { ".mjs", "c_like" },
    { ".mts", "c_like" },
    { ".cjs", "c_like" },
    { ".cts", "c_like" },
    { ".java", "c_like" },
    { ".m", "c_like" },
    { ".php", "c_like" },
    { ".dart", "c_like" },
    { ".go", "c_like" },
    { ".swift", "c_like" },
    { ".kt", "c_like" },
    { ".scala", "c_like" },
    { ".hx", "c_like" },
    { ".hxml", "c_like" },
    { ".zig", "c_like" },
    { ".zon", "c_like" },
    { ".jsonc", "c_like" },
    { ".rc", "c_like" },
    { ".lisp", "lisp_like" },
    { ".lsp", "lisp_like" },
    { ".cl", "lisp_like" },
    { ".scm", "lisp_like" },
    { ".rkt", "lisp_like" },
    { ".clj", "lisp_like" },
    { ".cljs", "lisp_like" },
    { ".cljc", "lisp_like" },
    { ".edn", "lisp_like" },
    { ".el", "lisp_like" },
    { ".ss", "lisp_like" },
    { ".hy", "lisp_like" },
    { ".janet", "lisp_like" },
    { ".fnl", "lisp_like" },
    { ".asm", "lisp_like" },
    { ".s", "lisp_like" },
    { ".sh", "shell_like" },
    { ".zsh", "shell_like" },
    { ".fish", "shell_like" },
    { ".dash", "shell_like" },
    { ".ksh", "shell_like" },
    { ".ash", "shell_like" },
    { ".tcsh", "shell_like" },
    { ".csh", "shell_like" },
    { ".rb", "shell_like" },
    { ".pl", "shell_like" },
    { ".pm", "shell_like" },
    { ".raku", "shell_like" },
    { ".rakumod", "shell_like" },
    { ".p6", "shell_like" },
    { ".jl", "shell_like" },
    { ".nim", "shell_like" },
    { ".cr", "shell_like" },
    { ".tf", "shell_like" },
    { ".nix", "shell_like" },
    { ".sls", "shell_like" },
    { ".cmake", "shell_like" },
    { ".yaml", "shell_like" },
    { ".yml", "shell_like" },
    { ".toml", "shell_like" },
    { ".ini", "shell_like" },
    { ".inp", "shell_like" },
    { ".ps1", "shell_like" },
    { ".bat", "shell_like" },
    { ".mak", "shell_like" },
    { ".desktop", "shell_like" },
    { ".cfg", "shell_like" },
    { ".conf", "shell_like" },
    { ".html", "markup" },
    { ".htm", "markup" },
    { ".xhtml", "markup" },
    { ".md", "markup" },
    { ".markdown", "markup" },
    { ".xml", "markup" },
    { ".xaml", "markup" },
    { ".svg", "markup" },
    { ".rst", "markup" },
    { ".tex", "markup" },
    { ".adoc", "markup" },
    { ".wxs", "markup" },
    { ".manifest", "markup" },
    { ".csproj", "markup" },
    { ".wixproj", "markup" },
    { ".txt", "text" },
    { ".json", "text" },
    { ".tutor", "text" },
    { ".in", "text" },
    { ".ti", "text" },
    { ".supp", "text" },
    { ".ok", "text" },
    { ".example", "text" },
    { ".dict", "text" },
    { ".cat", "text" },
    { ".1", "text" },
    { ".lock", "text" },
    { ".log", "text" },
    { ".csv", "text" },
    { ".py", "python" },
    { ".css", "css" },
    { ".scss", "css" },
    { ".sass", "css" },
    { ".less", "css" },
    { ".styl", "css" },
    { ".stylus", "css" },
    { ".pcss", "css" },
    { ".vim", "vim" },
    { ".lua", "lua" },
    { ".cmd", "cmd" },
    { ".jsx", "react" },
    { ".tsx", "react" },
    { ".build", "shell_like" },
    { ".bzl", "shell_like" },
    { ".d", "c_like" },
    { ".gleam", "c_like" },
    { ".glsl", "c_like" },
    { ".vert", "c_like" },
    { ".frag", "c_like" },
    { ".geom", "c_like" },
    { ".tesc", "c_like" },
    { ".tese", "c_like" },
    { ".comp", "c_like" },
    { ".groovy", "c_like" },
    { ".gvy", "c_like" },
    { ".hlsl", "c_like" },
    { ".fx", "c_like" },
    { ".fxh", "c_like" },
    { ".kts", "c_like" },
    { ".odin", "c_like" },
    { ".pony", "c_like" },
    { ".proto", "c_like" },
    { ".pug", "c_like" },
    { ".qml", "c_like" },
    { ".res", "c_like" },
    { ".resi", "c_like" },
    { ".sol", "c_like" },
    { ".sv", "c_like" },
    { ".svh", "c_like" },
    { ".typ", "c_like" },
    { ".vala", "c_like" },
    { ".vapi", "c_like" },
    { ".v", "c_like" },
    { ".vh", "c_like" },
    { ".wgsl", "c_like" },
    { ".awk", "shell_like" },
    { ".ex", "shell_like" },
    { ".exs", "shell_like" },
    { ".graphql", "shell_like" },
    { ".gql", "shell_like" },
    { ".hcl", "shell_like" },
    { ".pp", "shell_like" },
    { ".r", "shell_like" },
    { ".R", "shell_like" },
    { ".tcl", "shell_like" },
    { ".meson", "shell_like" },
    { ".wrap", "shell_like" },
    { ".nf", "shell_like" },
    { ".vue", "markup" },
    { ".red", "lisp_like" },
    { ".reds", "lisp_like" },
    { ".moon", "lua" },
    { ".hs", "haskell" },
    { ".lhs", "haskell" },
    { ".elm", "haskell" },
    { ".purs", "haskell" },
    { ".erl", "erlang" },
    { ".hrl", "erlang" },
    { ".f", "fortran" },
    { ".f90", "fortran" },
    { ".f95", "fortran" },
    { ".f03", "fortran" },
    { ".f08", "fortran" },
    { ".ada", "ada" },
    { ".ads", "ada" },
    { ".vhd", "ada" },
    { ".vhdl", "ada" },
    { ".ml", "ocaml" },
    { ".mli", "ocaml" },
    { ".fs", "ocaml" },
    { ".fsx", "ocaml" },
    { ".sml", "ocaml" },
    { ".sql", "sql" },
    { ".coffee", "coffeescript" },
    { ".pro", "prolog" },
    { ".wat", "wat" },
    { ".wast", "wat" },
    { ".cob", "cobol" },
    { ".cbl", "cobol" },
    { ".db", "text" },
    { ".sqlite", "text" },
    { ".sqlite3", "text" },
    { ".db3", "text" },
    { ".mdb", "text" },
    { ".accdb", "text" },
    { ".dump", "text" }
};

inline std::unordered_map<std::string, std::string_view> map_extension_name{
    { ".cpp", "C++" },
    { ".cxx", "C++" },
    { ".cc", "C++" },
    { ".c", "C" },
    { ".h", "C Header" },
    { ".hpp", "C++ Header" },
    { ".hxx", "C++ Header" },
    { ".inl", "C++ Header" },
    { ".rs", "Rust" },
    { ".cs", "C#" },
    { ".js", "JavaScript" },
    { ".ts", "TypeScript" },
    { ".mjs", "JavaScript (ESM)" },
    { ".mts", "TypeScript (ESM)" },
    { ".cjs", "JavaScript (CJS)" },
    { ".cts", "TypeScript (CJS)" },
    { ".java", "Java" },
    { ".m", "Objective-C" },
    { ".php", "PHP" },
    { ".dart", "Dart" },
    { ".go", "Go" },
    { ".swift", "Swift" },
    { ".kt", "Kotlin" },
    { ".scala", "Scala" },
    { ".hx", "Haxe" },
    { ".hxml", "Haxe" },
    { ".zig", "Zig" },
    { ".zon", "ZON" },
    { ".jsonc", "JSONC" },
    { ".rc", "RC" },
    { ".lisp", "Common Lisp" },
    { ".lsp", "Common Lisp" },
    { ".cl", "Common Lisp" },
    { ".scm", "Scheme" },
    { ".rkt", "Racket" },
    { ".clj", "Clojure" },
    { ".cljs", "Clojure" },
    { ".cljc", "Clojure" },
    { ".edn", "EDN" },
    { ".el", "Emacs Lisp" },
    { ".hy", "Hy" },
    { ".janet", "Janet" },
    { ".fnl", "Fennel" },
    { ".asm", "Assembly" },
    { ".s", "Assembly" },
    { ".sh", "Bash" },
    { ".zsh", "ZSH" },
    { ".fish", "Fish" },
    { ".dash", "Dash" },
    { ".ksh", "KSH" },
    { ".ash", "ASH" },
    { ".tcsh", "TCSH" },
    { ".csh", "CSH" },
    { ".rb", "Ruby" },
    { ".pl", "PL/I" },
    { ".pm", "PM" },
    { ".raku", "Raku" },
    { ".rakumod", "Raku" },
    { ".p6", "P6" },
    { ".jl", "Julia" },
    { ".nim", "Nim" },
    { ".cr", "Crystal" },
    { ".tf", "Tensor Flow" },
    { ".nix", "NIX" },
    { ".sls", "S/LS" },
    { ".cmake", "CMake" },
    { ".yaml", "YAML" },
    { ".yml", "YAML" },
    { ".toml", "TOML" },
    { ".ini", "INI" },
    { ".inp", "INP" },
    { ".ps1", "PWSH Script" },
    { ".bat", "CMD" },
    { ".mak", "Make" },
    { ".desktop", "Desktop File" },
    { ".cfg", "CFG" },
    { ".conf", "Config File" },
    { ".html", "HTML" },
    { ".htm", "HTML" },
    { ".xhtml", "XHTML" },
    { ".md", "Markdown" },
    { ".markdown", "Markdown" },
    { ".xml", "XML" },
    { ".xaml", "XAML" },
    { ".svg", "SVG" },
    { ".rst", "RST" },
    { ".tex", "TeX" },
    { ".adoc", "ASCII Doc" },
    { ".wxs", "WIX" },
    { ".manifest", "Manifest" },
    { ".csproj", "C# Project" },
    { ".wixproj", "WIX Project" },
    { ".txt", "Text" },
    { ".json", "JSON" },
    { ".tutor", "Tutor" },
    { ".in", "IN" },
    { ".ti", "TI" },
    { ".supp", "SUPP" },
    { ".ok", "Text" },
    { ".example", "Text" },
    { ".dict", "Dictionary" },
    { ".cat", "Text" },
    { ".1", "Man" },
    { ".lock", "Lock File" },
    { ".log", "Log" },
    { ".py", "Python" },
    { ".css", "CSS" },
    { ".scss", "CSS" },
    { ".sass", "CSS" },
    { ".less", "CSS" },
    { ".styl", "CSS" },
    { ".stylus", "CSS" },
    { ".pcss", "CSS" },
    { ".vim", "VIM" },
    { ".lua", "Lua" },
    { ".cmd", "CMD" },
    { ".jsx", "JavaScript React" },
    { ".tsx", "TypeScript React" },
    { ".csv", "CSV" },
    { ".build", "Meson" },
    { ".bzl", "Bazel" },
    { ".d", "D" },
    { ".gleam", "Gleam" },
    { ".glsl", "GLSL" },
    { ".vert", "GLSL" },
    { ".frag", "GLSL" },
    { ".geom", "GLSL" },
    { ".tesc", "GLSL" },
    { ".tese", "GLSL" },
    { ".comp", "GLSL" },
    { ".groovy", "Groovy" },
    { ".gvy", "Groovy" },
    { ".hlsl", "HLSL" },
    { ".fx", "HLSL" },
    { ".fxh", "HLSL" },
    { ".kts", "Kotlin Script" },
    { ".odin", "Odin" },
    { ".pony", "Pony" },
    { ".proto", "Protocol Buffers" },
    { ".pug", "Pug" },
    { ".qml", "QML" },
    { ".res", "ReScript" },
    { ".resi", "ReScript" },
    { ".sol", "Solidity" },
    { ".sv", "SystemVerilog" },
    { ".svh", "SystemVerilog" },
    { ".typ", "Typst" },
    { ".vala", "Vala" },
    { ".vapi", "Vala" },
    { ".v", "Verilog" },
    { ".vh", "Verilog" },
    { ".wgsl", "WGSL" },
    { ".awk", "AWK" },
    { ".ex", "Elixir" },
    { ".exs", "Elixir" },
    { ".graphql", "GraphQL" },
    { ".gql", "GraphQL" },
    { ".hcl", "HCL" },
    { ".pp", "Puppet" },
    { ".r", "R" },
    { ".R", "R" },
    { ".tcl", "Tcl" },
    { ".meson", "Meson" },
    { ".wrap", "Meson" },
    { ".nf", "Nextflow" },
    { ".vue", "Vue" },
    { ".red", "Red" },
    { ".reds", "Red" },
    { ".moon", "MoonScript" },
    { ".hs", "Haskell" },
    { ".lhs", "Haskell" },
    { ".elm", "Elm" },
    { ".purs", "PureScript" },
    { ".erl", "Erlang" },
    { ".hrl", "Erlang" },
    { ".f", "Fortran" },
    { ".f90", "Fortran" },
    { ".f95", "Fortran" },
    { ".f03", "Fortran" },
    { ".f08", "Fortran" },
    { ".ada", "Ada" },
    { ".ads", "Ada" },
    { ".vhd", "VHDL" },
    { ".vhdl", "VHDL" },
    { ".ml", "OCaml" },
    { ".mli", "OCaml" },
    { ".fs", "F#" },
    { ".fsx", "F#" },
    { ".sml", "Standard ML" },
    { ".sql", "SQL" },
    { ".coffee", "CoffeeScript" },
    { ".pro", "Prolog" },
    { ".wat", "WebAssembly" },
    { ".wast", "WebAssembly" },
    { ".cob", "COBOL" },
    { ".cbl", "COBOL" },
    { ".db", "Database" },
    { ".sqlite", "SQLite" },
    { ".sqlite3", "SQLite" },
    { ".db3", "SQLite" },
    { ".mdb", "Access" },
    { ".accdb", "Access" },
    { ".dump", "Database Dump" }
};

inline std::unordered_map<std::string, std::string> map_extension_icon{
    { ".cpp", "" },      { ".cxx", "" },     { ".cc", "" },      { ".c", "" },
    { ".h", "" },        { ".hpp", "" },     { ".hxx", "" },     { ".inl", "" },
    { ".rs", "" },       { ".cs", "" },      { ".js", "" },      { ".ts", "" },
    { ".mjs", "" },      { ".mts", "" },     { ".cjs", "" },     { ".cts", "" },
    { ".java", "" },     { ".m", "" },       { ".php", "" },     { ".dart", "" },
    { ".go", "" },       { ".swift", "" },   { ".kt", "" },      { ".scala", "" },
    { ".hx", "" },       { ".hxml", "" },    { ".zig", "" },     { ".zon", "" },
    { ".jsonc", "" },    { ".lisp", "" },    { ".lsp", "" },     { ".cl", "" },
    { ".scm", "" },      { ".clj", "" },     { ".cljs", "" },    { ".cljc", "" },
    { ".el", "" },       { ".fnl", "" },     { ".asm", "" },     { ".s", "" },
    { ".sh", "" },       { ".zsh", "" },     { ".fish", "" },    { ".dash", "" },
    { ".ksh", "" },      { ".ash", "" },     { ".tcsh", "" },    { ".csh", "" },
    { ".rb", "" },       { ".jl", "" },      { ".nim", "" },     { ".cr", "" },
    { ".tf", "" },       { ".nix", "󱄅" },    { ".cmake", "" },   { ".yaml", "" },
    { ".yml", "" },      { ".toml", "" },    { ".ini", "" },     { ".ps1", "" },
    { ".bat", "" },      { ".mak", "" },     { ".desktop", "" }, { ".conf", "" },
    { ".html", "" },     { ".htm", "" },     { ".xhtml", "" },   { ".md", "" },
    { ".markdown", "" }, { ".xml", "󰗀" },    { ".xaml", "󰙳" },   { ".svg", "󰜡" },
    { ".tex", "" },      { ".wxs", "" },     { ".csproj", "" },  { ".wixproj", "" },
    { ".json", "" },     { ".1", "" },       { ".lock", "" },    { ".log", "" },
    { ".py", "" },       { ".css", "" },     { ".scss", "" },    { ".sass", "" },
    { ".less", "" },     { ".styl", "" },    { ".stylus", "" },  { ".pcss", "" },
    { ".vim", "" },      { ".lua", "" },     { ".cmd", "" },     { ".exe", "" },
    { ".jsx", "" },      { ".tsx", "" },     { ".csv", "" },     { ".pdf", "" },
    { ".zip", "" },      { ".rar", "" },     { ".7z", "" },      { ".tar", "" },
    { ".gz", "" },       { ".bz2", "" },     { ".xz", "" },      { ".z", "" },
    { ".lz", "" },       { ".lzma", "" },    { ".lzo", "" },     { ".zst", "" },
    { ".dmg", "" },      { ".pkg", "" },     { ".xip", "" },     { ".cab", "" },
    { ".msi", "" },      { ".wim", "" },     { ".deb", "" },     { ".rpm", "" },
    { ".snap", "" },     { ".jar", "" },     { ".war", "" },     { ".ear", "" },
    { ".aar", "" },      { ".apk", "" },     { ".ipa", "󰀷" },    { ".whl", "" },
    { ".egg", "" },      { ".iso", "󰗮" },    { ".img", "󰗮" },    { ".bin", "󰗮" },
    { ".cue", "󰗮" },     { ".nrg", "󰗮" },    { ".vhd", "󰗮" },    { ".vmdk", "󰗮" },
    { ".jpg", "" },      { ".jpeg", "" },    { ".png", "" },     { ".bmp", "" },
    { ".tiff", "" },     { ".tif", "" },     { ".webp", "" },    { ".avif", "" },
    { ".heif", "" },     { ".heic", "" },    { ".ico", "" },     { ".cur", "" },
    { ".psd", "" },      { ".xcf", "" },     { ".raw", "" },     { ".cr2", "" },
    { ".nef", "" },      { ".arw", "" },     { ".dng", "" },     { ".gif", "󰵸" },
    { ".mp4", "" },      { ".mkv", "" },     { ".avi", "" },     { ".mov", "" },
    { ".wmv", "" },      { ".flv", "" },     { ".mpeg", "" },    { ".mpg", "" },
    { ".3gp", "" },      { ".3g2", "" },     { ".m2ts", "" },    { ".vob", "" },
    { ".ogv", "" },      { ".rm", "" },      { ".rmvb", "" },    { ".asf", "" },
    { ".divx", "" },     { ".hevc", "" },    { ".h264", "" },    { ".h265", "" },
    { ".f4v", "" },      { ".mxf", "" },     { ".roq", "" },     { ".drc", "" },
    { ".amv", "" },      { ".webm", "" },    { ".m4v", "" },     { ".mp3", "" },
    { ".aac", "" },      { ".m4a", "" },     { ".ogg", "" },     { ".opus", "" },
    { ".wma", "" },      { ".amr", "" },     { ".ac3", "" },     { ".flac", "" },
    { ".alac", "" },     { ".wav", "" },     { ".aiff", "" },    { ".aif", "" },
    { ".ape", "" },      { ".wv", "" },      { ".tta", "" },     { ".oga", "" },
    { ".mka", "" },      { ".ra", "" },      { ".mid", "" },     { ".midi", "" },
    { ".rmi", "" },      { ".dsf", "" },     { ".dff", "" },     { ".caf", "" },
    { ".pcm", "" },      { ".ttf", "" },     { ".otf", "" },     { ".woff", "" },
    { ".woff2", "" },    { ".fon", "" },     { ".fnt", "" },     { ".pfb", "" },
    { ".pfm", "" },      { ".bdf", "" },     { ".pcf", "" },     { ".cff", "" },
    { ".sfd", "" },      { ".ninja", "󰝴" },  { ".bzl", "" },     { ".d", "" },
    { ".groovy", "" },   { ".gvy", "" },     { ".kts", "" },     { ".pug", "" },
    { ".qml", "" },      { ".res", "" },     { ".resi", "" },    { ".sol", "" },
    { ".sv", "" },       { ".svh", "" },     { ".typ", "" },     { ".vala", "" },
    { ".vapi", "" },     { ".v", "" },       { ".vh", "" },      { ".awk", "" },
    { ".ex", "" },       { ".exs", "" },     { ".graphql", "" }, { ".gql", "" },
    { ".hcl", "" },      { ".pp", "" },      { ".r", "" },       { ".R", "" },
    { ".vue", "" },      { ".moon", "" },    { ".hs", "" },      { ".lhs", "" },
    { ".elm", "" },      { ".purs", "" },    { ".erl", "" },     { ".hrl", "" },
    { ".f", "" },        { ".f90", "" },     { ".f95", "" },     { ".f03", "" },
    { ".f08", "" },      { ".ml", "" },      { ".mli", "" },     { ".fs", "" },
    { ".fsx", "" },      { ".sql", "" },     { ".coffee", "" },  { ".db", "" },
    { ".sqlite", "" },   { ".sqlite3", "" }, { ".db3", "" },     { ".mdb", "" },
    { ".accdb", "" },    { ".dump", "" }
};

inline std::unordered_map<std::string, std::string> map_directory_icon{
    { ".git", "" },     { "include", "󱁿" },   { "src", "󰣞" },    { "node_modules", "" },
    { ".config", "󱁿" }, { ".vscode", "󰨞" },   { ".idea", "" },   { "cmake", "" },
    { "scripts", "󰴉" }, { "docs", "󱂷" },      { "doc", "󱂷" },    { "assets", "󰉏" },
    { "res", "󰉏" },     { "resources", "󰉏" }, { "public", "󰙉" }, { "test", "󰙨" },
    { "tests", "󰙨" },   { "__tests__", "󰙨" }, { "debug", "󰃤" },  { "benchmark", "󰅒" },
    { "api", "󱂛" },     { "client", "󱩛" },    { "server", "" },  { ".github", "" },
    { "build", "" },    { "out", "" },
};

} // namespace mappings

} // namespace fima
