name: Build and deploy program

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CMAKE_GENERATOR: Ninja


jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Setup C++
        uses: aminya/setup-cpp@8170d66c458f4a045220b7b0966c10940bb2a15d
        with:
          ninja: true
          conan: true
          cmake: "3.31.0"
          gcc: "15"

      - name: Cache or restore conan dependencies
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: conan-${{ runner.os }}-${{ hashFiles('conan.lock') }}
          restore-keys: |
            conan-${{ runner.os }}-

      - name: Setup conan profile
        run: conan profile detect --force

      - name: Build the program
        run: ./scripts/release/build.sh

      - name: Build DEB Package
        run: cd build && cpack -G DEB && cd ..

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          path: build/fima
          name: Binary

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          path: build/fima_*.deb
          name: DEB

  deploy-to-apt:
    needs: build-and-test
    runs-on: ubuntu-24.04
    environment:
      name: deployment
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_KEY_SECRET }}
      AWS_DEFAULT_REGION: auto
      AWS_ENDPOINT_URL: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
    steps:
      - name: Checkout repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0

      - name: Check for tag
        id: check_tag
        run: |
          if git tag --points-at HEAD~ | grep -q .; then
            echo "is_tag=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_tag=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Download DEB artifact
        if: steps.check_tag.outputs.is_tag == 'true'
        uses: actions/download-artifact@v4
        with:
          name: DEB
          path: dist

      - name: Set config from env var
        if: steps.check_tag.outputs.is_tag == 'true'
        run: echo $APTLY_CONFIG > ~/.aptly.conf

      - name: Download aptly db and pool from R2
        if: steps.check_tag.outputs.is_tag == 'true'
        run: aws s3 sync s3://apt-repository/.aptly /home/runner/.aptly

      - name: Import GPG signing key
        if: steps.check_tag.outputs.is_tag == 'true'
        run: |
          echo "${{ secrets.APT_GPG_PRIVKEY }}" | base64 -d | gpg --batch --import
          mkdir -p ~/.gnupg
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent

      - name: Install aptly
        if: steps.check_tag.outputs.is_tag == 'true'
        run: |
          curl -o- https://www.aptly.info/pubkey.txt | sudo gpg --dearmor -o /usr/share/keyrings/aptly-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/aptly-archive-keyring.gpg] http://repo.aptly.info/ squeeze main" | sudo tee /etc/apt/sources.list.d/aptly.list
          sudo apt update
          sudo apt install -y aptly

      - name: Add DEB to aptly
        if: steps.check_tag.outputs.is_tag == 'true'
        run: aptly repo add scsdc dist/*.deb

      - name: Publish DEB to R2
        env:
          GPG_PASS: ${{ secrets.APT_GPG_PASS }}
        if: steps.check_tag.outputs.is_tag == 'true'
        run: "aptly publish repo -passphrase=$GPG_PASS -signed-by=FD189A3382E4B62273291C3FB336BC50F0D41CC7 -distribution=stable scsdc s3:r2:"

      - name: Upload Aptly DB and Pool to S3
        if: steps.check_tag.outputs.is_tag == 'true'
        run: aws s3 sync /home/runner/.aptly/db s3://.aptly/db && aws s3 sync /home/runner/.aptly/pool s3://.aplty/pool

