name: build and test the program

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  CMAKE_GENERATOR: Ninja

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          ninja: true
          conan: true
          cmake: "3.31.0"
          gcc: "15"

      - name: Setup conan profile
        run: conan profile detect

      - name: Build the program
        run: ./scripts/main.sh -b

      - name: Test the program
        run: ./scripts/test.sh
