name: build and test the program

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  CMAKE_GENERATOR: Ninja

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create theme and config file
        run: |
          mkdir -p ~/.config/fima
          cat > ~/.config/fima/config.toml << 'EOF'
          [icons.files]
          cpp = "󰙲"
          [icons.dirs]
          custom_name = ""
          [icons.name]
          "*cat*" = ""
          EOF
          cat > ~/.config/fima/theme.toml << 'EOF'
          [general]
          primary = [92, 243, 11]
          secondary = "#9482af"
          border = "light gray"
          info = "white"
          warning = "blue"
          error = "light blue"

          [specific]
          directory = "cyan"
          executable = "light cyan"
          symlink = "green"
          archive = "light green"
          media = "magenta"
          normal_file = "light magenta"

          [permissions]
          read = "red"
          write = "light red"
          execute = "yellow"
          null = "light yellow"

          [ls]
          permissions = "black"
          size = "dark gray"
          EOF

      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          ninja: true
          conan: true
          cmake: "3.31.0"
          gcc: "16"

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Setup conan profile
        run: conan profile detect

      - name: Build the program
        run: ./scripts/build_tests.sh

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
