name: Build and test the program

on:
  pull_request:
    branches:
      - main

env:
  CMAKE_GENERATOR: Ninja

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Create theme and config file
        run: |
          mkdir -p ~/.config/fima
          cat > ~/.config/fima/config.toml << 'EOF'
          [icons.files]
          cpp = "󰙲"
          [icons.dirs]
          custom_name = ""
          [icons.name]
          "*cat*" = ""
          EOF
          cat > ~/.config/fima/theme.toml << 'EOF'
          [general]
          primary = [92, 243, 11]
          secondary = "#9482af"
          border = "light gray"
          info = "white"
          warning = "blue"
          error = "light blue"

          [specific]
          directory = "cyan"
          executable = "light cyan"
          symlink = "green"
          archive = "light green"
          media = "magenta"
          normal_file = "light magenta"

          [permissions]
          read = "red"
          write = "light red"
          execute = "yellow"
          null = "light yellow"

          [ls]
          permissions = "black"
          size = "dark gray"
          EOF

      - name: Setup C++
        uses: aminya/setup-cpp@8170d66c458f4a045220b7b0966c10940bb2a15d
        with:
          ninja: true
          conan: true
          cmake: "3.31.0"
          gcc: "15"

      - name: Cache or restore conan dependencies
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: conan-${{ runner.os }}-${{ hashFiles('conan.lock') }}
          restore-keys: |
            conan-${{ runner.os }}-

      - name: Setup conan profile
        run: conan profile detect --force

      - name: Build the program
        run: ./scripts/tests/build.sh

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
